### PR TITLE
Fix typos - Update string_types.jl

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
There might be more, but I was checking the code for other things.

It seems like a nice package! You can only have one condition for each typo, e.g. lower case, or you just use a regex? For e.g. numbers you might want to have a min and a max. Those constraints are maintained at runtime, not just for construction? Then have a performance cost... but yes I've been thinking of my own float type for only positive numbers. You can actually get away with then just a performance cost, exceptions on minus, and other operators unchanged.

**Comment by gryumov** [comment]
@PallHaraldsson, hi, thanks for the PR. I will get back to you about the license a bit later.

**Review by gryumov — APPROVED** [review]

**Comment by artememelin** [comment]
@PallHaraldsson Hi, if I understood the question correctly, then no, you can impose multiple conditions on a type, for example:
```julia
StringLowerCase{StringMinLength{StringMaxLength{String,6},3}}("abcde")

NumberPositive{NumberLessOrEqual{NumberOdd{Float64},10}}(7)
```

> Those constraints are maintained at runtime, not just for construction?

Conditions are checked only when an object is created or when a new value is assigned to a field of some type (in fact, this is exactly what the package was designed for)
```julia
mutable struct MyStruct
    some_field::NumberPositive{Float64}
end

a = MyStruct(1.0)

# Yes
a.some_field = 2.0

# No
a.some_field = -1.0
```

And of course it won’t be possible to do something like
```julia
b = NumberPositive{Float64}(1.0)

# No
b.value = 2.0
```
because constraint types are immutable

**Comment by gryumov** [comment]
https://github.com/bhftbootcamp/BoundTypes.jl/pull/7

@PallHaraldsson сс

**Pull request merged**
